name: "CI"

on: [push, pull_request]

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: docker.io/bilelmoussaoui/flatpak-github-actions
      options: --privileged
    steps:
    - uses: actions/checkout@master
    - uses: bilelmoussaoui/flatpak-github-actions@master
      with:
        bundle: "akira-dev.flatpak"
        manifest-path: "build-aux/flatpak/com.github.akiraux.akira.json"
        app-id: "com.github.akiraux.akiraDevel"
        flatpak-module: "akira"
